[package]
name = "site"
version = "0.1.0"
authors = ["Pontus Laestadius <pontus.laestadius@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_codegen = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.0"
features = ["tera_templates"]

